# Generated by Django 3.2.13 on 2023-06-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=255)),
                ('second_flavor', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_two_flavors', models.BooleanField(default=False)),
            ],
        ),
    ]
