# Generated by Django 3.2.13 on 2023-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='ingredients.Ingredients'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
