# Generated by Django 3.2.13 on 2023-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(default='12', max_length=14),
            preserve_default=False,
        ),
    ]
