# Generated by Django 3.2.13 on 2023-06-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='ingredient',
            new_name='ingredient_name',
        ),
    ]
